# Generated by Django 5.2.17 on 2026-10-08 19:59

from django.db import migrations

DEFAULT_NAME = "Main Warehouse"


def one_warehouse_per_business(apps, schema_editor):
    Business = apps.get_model("accounts", "Business")
    Warehouse = apps.get_model("inventory", "Warehouse")
    Product = apps.get_model("inventory", "Product")

    for business in Business.objects.all():
        warehouses = list(
            Warehouse.objects.filter(business=business).order_by("created_at")
        )
        if warehouses:
            main = warehouses[0]
            extra_ids = [w.id for w in warehouses[1:]]
            if extra_ids:
                Product.objects.filter(warehouse_id__in=extra_ids).update(warehouse=main)
                Warehouse.objects.filter(id__in=extra_ids).delete()
        else:
            main = Warehouse.objects.create(business=business, name=DEFAULT_NAME)

        Product.objects.filter(business=business, warehouse__isnull=True).update(warehouse=main)


class Migration(migrations.Migration):

    dependencies = [
            ('inventory', '0003_product_image'),
    ]

    operations = [
        migrations.RunPython(one_warehouse_per_business, migrations.RunPython.noop),
    ]