# Generated by Django 5.2.17 on 2026-10-08 21:12

import django.core.validators
import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_employeeinvite'),
        ('inventory', '0004_one_warehouse_per_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='uniq_warehouse_name_per_business',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[inventory.models.validate_image_size, inventory.models.validate_image_content, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='accounts.business'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default='Main Warehouse', max_length=100),
        ),
    ]
