# Generated by Django 5.2.17 on 2026-10-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_outlet_dispatchnote_stockmovement_dispatchitem_and_more'),
    ]

    operations = [
    ]

def backfill(apps, schema_editor):
  Product = apps.get_model("inventory", "Product")
  StockMovement = apps.get_model("inventory", "StockMovement")
  movements = [
    StockMovement(
      business_id=p.business_id,
      product_id=p.id,
      quantity_change=p.quantity,
      balance_after=p.quantity,
      reason="opening_balance",
      note="Backfilled from existing quantity",
    )
    for p in Product.objects.filter(quantity__gt=0).iterator()
  ]
  StockMovement.objects.bulk_create(movements, batch_size=500)


class Migration(migrations.Migration):
  dependencies = [("inventory", "0006_outlet_dispatchnote_stockmovement_dispatchitem_and_more")]
  operations = [migrations.RunPython(backfill, migrations.RunPython.noop)]
